apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'nginx-alpine'
spec:
  destination:
    namespace: 'nginx-alpine'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'exercises/manifests'
    repoURL: 'https://github.com/udacity/nd064_course_1'
    targetRevision: HEAD
  project: 'default'
